### ISSUE TITLE
Support from_reader() like serde_json::from_reader()

### ISSUE THREAD

**Issue by pymongo** [cloudwego/sonic-rs#43]
**Is your feature request related to a problem? Please describe.**

Any function to deserialize from a TcpStream or File?

**Comment by liuq19** [comment]
there are no existing functions as `from_reader` , because the streaming parse is slower,  and we recommend to read an I/O stream completely into memory and then applying `from_str` or `from_slice`.

**Comment by CPunisher** [comment]
@liuq19 I think there are two ways:
1. Call `io::Read::read_to_end` to save data in a buffer, and call `from_slice`. This is a simple way that references https://github.com/simd-lite/simd-json/blob/dd7fc44f5526e3e2abe0ebba53bc1faed501a128/src/serde.rs#L143C8-L143C19.
2. Adapt `Reader` trait for `io::Read`. This could be complex. We have to reassign `Reader` trait API and do refactor. `serde` do this way since it deserializes json char by char, which consists of the feature of `io::Read`. But we may get better performance.

**Comment by liuq19** [comment]
thanks, I prefer the first method, could you try it?
